alias dpa='docker ps -a'
alias drm='docker rm $(docker ps -qf status=exited)'
alias dri='docker rmi '
alias dim='docker images'
alias dke='docker'
alias dkl='docker logs '
alias dkr='docker run '
alias dka='docker attach '
alias dkt='docker tag '
